empty=set()
s=input("Enter no first")
empty.add(int(s))
s=input("Enter no second")
empty.add(int(s))
s=input("Enter no third")
empty.add(int(s))
s=input("Enter no fourth")
empty.add(int(s))
print(empty)